### ISSUE TITLE
suit_isolate_seg (orientation problem?)

### ISSUE THREAD

**Issue by ghost** [jdiedrichsen/suit#12]
Dear SUIT experts, 
I am using SUIT to obtain an atlas-based parcellation of cerebellar regions in patients and controls.
My pipeline includes automatic reorientation of T1w volumes so that the origin is set near to the AC using the hmri_autoreorient script (https://github.com/hMRI-group/hMRI-toolbox/blob/master/hmri_autoreorient.m), which rigidly registers the T1w images to the spm MNI template, and resampling to 1mm isotropic resolution and 181x217x181 matrix using the resize_img script (http://www0.cs.ucl.ac.uk/staff/G.Ridgway/vbm/resize_img.m).
When running suit_isolate_seg on preprocessed images, the cropped image (c_T1w.nii) looks perfectly fine but both the mask and segmentation files look empty, preventing subsequent processing steps.
Strangely enough, when working on raw T1w images, the isolation/segmentation procedure seems to work perfectly fine.
At first I thought of a possible orientation problem (according to spm_orientations, raw images are in LPI orientation, but the spm template is RPI, even if preprocessed T1w images are still in LPI orientation), so I tried to bring the spm template to LPI orientation before registering raw images to it, but nothing seemed to change.

Do you have any idea of what the problem could be here?

Thank you so much in advance for your help,
Giuseppe

**Comment by jdiedrichsen** [comment]
very strange - would you be able to attach the T1w image resliced into MNI space, so we can replicate the problem here?
