### ISSUE TITLE
suit_reslice_dartel_inv gives very small reconstruction images in individual spaces

### ISSUE THREAD

**Issue by Vincent-wq** [jdiedrichsen/suit#13]
Hi, 
I have been tryied to use SUIT to segment the cerebellar of PPMI subjects, it works fine for 60% of my subjcets, but ends up by giving extremely small invidual space segmentations, the shape of this image looks ok, but the overall volume is super small, almsot not visable compared to the original T1 image. 
Here are more details:
Take sub-3000 (you can find this subject in then open PPMI dataset) as an example, I did the following steps:
1. Segment T1 image with ```suit_isolate_seg``` into gray and white mater, it also gives cropped images;
all these images align well with each other;
2. Normalization with ```suit_normalize_dartel```, it gives u_a_sub-3000_run-1_desc-preproc_T1w_seg1.nii and Affine_sub-3000_run-1_desc-preproc_T1w_seg1.mat; 
I would like to check the results of this step, any suggestions?
3. Get individual cerebellar segmentation with ```suit_reslice_dartel_inv```, the input is the results from step 2 and original T1 or cerebellar gray matter as reference, SUIT_ATLAS as resample,
The output iw_Lobules-SUIT_u_a_sub-3000_run-1_desc-preproc_T1w_seg1.nii should be aligned with the original T1, but it is way smaller thus give very small lobular volumns. 

Any idea why this happen and how could we solve this problem? My script works for more than 60% of my subjects but has this issue for the rest 30%+ subjects.
Great thanks for you attention and time.
Cheers,
Vincent

**Comment by crhernandezc** [comment]
Hi vincent, Have you check that all the images are in LPI orientation and that the origin of the image is on the anterior commissure? if not, the normalization will fail. You can check that (your step 2), by using suit_reslice_dartel, and you can use the original t1 as the input, and the pcereb as the cerebellar mask. The result will be the normalized T1 in suit space, you can compare that to the SUIT template to visually check the normalization.

**Comment by Vincent-wq** [comment]
Yes, thanks for your sugestions. You are right about the cause of the normalization problem, after I mannally reorient the images to the AC point (and keep AC-PC line horizontal so that cerebellum is included in the lower posterior part of the image), only 2 subjects were still giving problems even after reorientation. The heads of these images were pitching too much. 
It seems SUIT is trying to crop the image from the origin and presevrve the lower anterior part (assuming cerebellum is completely included), then do the normalization, it saves a lot of time and gives beter results. Is that right?
Thanks again for your explaination.
Cheers,
Vincent
