### ISSUE TITLE
using data in SUIT space for FEAT group analysis?

### ISSUE THREAD

**Issue by aachoudhury** [jdiedrichsen/suit#14]
I am using single-session multi-subject task-based data to compare brainstem activation among different groups. Is there a way to normalize both anatomical and functional scans to SUIT space and use them for higher-level analysis through FSL FEAT?

**Comment by jdiedrichsen** [comment]
Hi, 
Sure -this should be no problem. You would need to install SPM + SUIT - and after the first level analysis simply reslice all the relevant functional maps from FSL before submitting them to FEAT. 
I'm not using FSL for my linear modeling, but I hope you can post an example script here if you figure it out! 

Joern

**Comment by aachoudhury** [comment]
Hello,

Following up on this: as suggested, I've been reslicing the relevant functional maps from first level analysis (FSL FEAT) into SUIT space before submitting them for higher level analysis. This method worked great and I was able to complete a group analysis in SUIT space using FEAT without any apparent issues.

However, lately I've been having issues after using the "suit_reslice_dartel" command. I keep experiencing the same problem where the resliced output files include NaN voxels, primarily along the boundaries of the image. If ignored and submitted to FEAT for higher level analysis, then the group maps also include NaN voxels that for some reason are found within the brainstem and obscure areas of signal activation.

I've tried zero'ing the NaN voxels found in the resliced subject-level images, but then I get changes in the group activation maps that don't appear to be correct. Is there anything else I can try to troubleshoot the NaN voxels after running "suit_reslice_dartel"?

Thanks,
AC

**Comment by jdiedrichsen** [comment]
The trick is just to replace the NaN's with zeros (for contrasts) BEFORE reslicing. If fname is a cell array of file names, just run the following code: 

for i=1:length(fname)
    V=spm_vol(fname{i})
    X=spm_read_vols(V)
    X(isnan(X))=0
spm_write_vol(V,X)
Then do  suit_reslice dartel and (if neessary) smooth. 

This way you won't loose data by interpolation with NaNs

**Comment by aachoudhury** [comment]
Hi Dr. Diedrichsen,

Thank you for your response! I ran the code as suggested, however, I'm still getting NaN values in my resliced images (in the same manner as described earlier). I'm not sure why this continues to be the case, especially since there don't appear to be any NaN values in the original functional scans before reslicing. 

Is there anything else I can try to troubleshoot this?

Thanks,
AC
