### ISSUE TITLE
Segmentation Issues

### ISSUE THREAD

**Issue by John3290** [jdiedrichsen/suit#15]
Hello,

I am using the newest version of SUIT to process a cohort of children between 3-12 years old. I used the GUI and the Segmentation & Isolation step of the processing stream within the SUIT toolbox. 

Segmentation does not seem to be working for these scans such that the inferior portions of the cerebellum are consistently not covered by the gray matter probability maps. See an example of the error we have seen in our subjects below:

![CBM3](https://user-images.githubusercontent.com/45977820/131707618-dfa4e0f8-8e3a-4a75-ad64-ff919ca9041d.png)
![CBM2](https://user-images.githubusercontent.com/45977820/131707620-18d5ffc8-fe9b-402a-b76b-4b5af408c5ff.png)
![CBM1](https://user-images.githubusercontent.com/45977820/131707621-01e8a00a-bc09-4130-b239-8b90f260cd07.png)

What are your suggestions moving forward to correct this error? Is there a setting within SUIT we could use to fix this issue?

Thanks,

Chelsea

**Comment by jdiedrichsen** [comment]
Hi Chelsea, 

sorry for the late reply... I would assume that the problem arises here, because SUIT is using a template and tissue prior that is appropriate for the adult brain, rather than 3-6 year olds. We have not used or tested any kids data - for the neonatal @crhernandezc has developed SUIT-N, but this will likely also not much better (although you could try it). 

If you can find a template + tissue probability map for the desired age bracket, we can help you to incorporate it into the SUIT pipeline. 

Joern

**Comment by crhernandezc** [comment]
Hi Chelsea,
Have you run an intensity and homogeneity correction in your images before running suit? That preprocessing might help the segmentation. Until we don't include the longitudinal templates to SUIT subjects younger than 4 years might be problematic, Like Jorn mentioned we have the neonatal version but that only works for babies younger than one year of age. Good luck!

**Comment by Keikokunitoki** [comment]
Hi everyone,
I'm having a similar problem with a pediatric cohort. We are working with ABCD study baseline data(9-10-year-old, N=11,000+total, and currently using European genetic origin N=5,000+).
I've tested for raw, bias-corrected, and motion+bias+intensity corrected images but there's not that much improvement. I also tried with another cohort age 18+ and they look much better. 
Do you have any other suggestions to improve the quality if you have? Also, I'd like to know how it'll be like to incorporate an age-appropriate template + tissue probability map.

![ABCDsample1s](https://user-images.githubusercontent.com/54902138/133633535-3857f01d-025c-4403-9eb0-95cc15176108.png)
![ABCDsample2s](https://user-images.githubusercontent.com/54902138/133633553-70d0e75f-0164-4930-ba89-310bd8150f98.png)

**Comment by crhernandezc** [comment]
Hi Keiko
Currently, there is not much we can do with that problem, However, I am planning to create a new longitudinal toolbox using several templates over lifespan, It might take some time since I am trying to get sample data from each year of life. If you want to use your own template it can be done using the optional arguments in the isolation function, Just be sure that the different segments in the new template are the same tissue type of the default. Best

**Comment by Keikokunitoki** [comment]
Thank you so much for your comments! It'll be so nice if we could have a longitudinal toolbox in the future since our lab is interested in neurodevelopment.
In a mean time, I'd like to try with our own template and checked "/spm12/toolbox/suit/templates/". It seems you used DARTEL to make them but they doesn't look like the usual SPM settings with 6 tissue types (gm, wm, CSF, soft tissue...). Is there any special way to make the TPM for SUIT? Also, there's a whole-brain TPM age 11.5 but I guess it'll be not ideal to use a part of the TPM. Is that correct?

**Comment by SEChang523** [comment]
Hi @crhernandezc and @jdiedrichsen , thank you for your responses! @crhernandezc , in terms of sample data from each year of life during childhood, how many datasets would you need to create the templates? I have longitudinal scans from children (control, stuttering) ranging from 3-12yrs (Chelsea is one of my students). Thanks

**Comment by crhernandezc** [comment]
@SEChang523 The more the better, I am thinking to have at least 50 healthy subjects per template (of each time point). Please email me and we can have a conversation.

**Comment by yenwchen** [comment]
Hi! We had the similar issue that some subjects' segmentation didn't cover the entire cerebellum, and are wondering if there is a solution. We have adolescents whose age ranges between 13 - 17. We were trying to adjust the bounding box ('bb') for suit_isolate_seg. The missed coverage was mainly at the posterior part of the cerebellum. We found that when we set the posterior coordinate that exceeded -126, the resultant brain box for segmentation became weird (missed the entire cerebellum). Please find the attached image from one of our subject (age = 17). The blue box used bb = [-76 76; -126 -50; -50 40], and the red box used bb = [-76 76; -130 -50; -50 40]. We'd greatly appreciate it if you can provide inputs and guidance. Thank you. 
<img width="673" alt="Screen_Shot_2024-02-07_at_11 42 47_AM (1)" src="https://github.com/jdiedrichsen/suit/assets/92695137/0b8e07c9-e1cb-4f14-a908-1e0d0356a144">

**Comment by yenwchen** [comment]
Hi! We had the similar issue that some subjects' segmentation didn't cover the entire cerebellum, and are wondering if there are updates and solutions. We have adolescents whose age ranges between 13 - 17. We tried to adjust the bounding box ('bb') for suit_isolate_seg. The missed coverage was mainly at the posterior part of the cerebellum. We found that when we set the posterior coordinate < -126, the resultant brain box for segmentation became weird (missed the entire cerebellum). Please find the attached image from one of our subject (age = 17). The blue box used bb = [-76 76; -126 -50; -50 40], and the red box used bb = [-76 76; -130 -50; -50 40]. We'd greatly appreciate it if you can provide inputs and guidance. Thank you!
![Screenshot 2024-02-14 at 5 58 47 PM](https://github.com/jdiedrichsen/suit/assets/92695137/3ee51547-f8a9-466c-817c-1f30ca137629)

**Comment by crhernandezc** [comment]
> Hi! We had the similar issue that some subjects' segmentation didn't cover the entire cerebellum, and are wondering if there are updates and solutions. We have adolescents whose age ranges between 13 - 17. We tried to adjust the bounding box ('bb') for suit_isolate_seg. The missed coverage was mainly at the posterior part of the cerebellum. We found that when we set the posterior coordinate < -126, the resultant brain box for segmentation became weird (missed the entire cerebellum). Please find the attached image from one of our subject (age = 17). The blue box used bb = [-76 76; -126 -50; -50 40], and the red box used bb = [-76 76; -130 -50; -50 40]. We'd greatly appreciate it if you can provide inputs and guidance. Thank you! ![Screenshot 2024-02-14 at 5 58 47 PM](https://private-user-images.githubusercontent.com/92695137/304902235-3ee51547-f8a9-466c-817c-1f30ca137629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDE4NDQsIm5iZiI6MTcwODAwMTU0NCwicGF0aCI6Ii85MjY5NTEzNy8zMDQ5MDIyMzUtM2VlNTE1NDctZjhhOS00NjZjLTgxN2MtMWYzMGNhMTM3NjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDEyNTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTViMTU0MTBiMDRiYWI0ODY5MGU5NTI0Y2UyYzY5ZDE5NmIyZTZkMTIyNWRhNWVkMWViM2ZkNTM1Nzc5YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vcm3JzMcmxrV9_NqYnATyCffRM_F38dcDo6WSYrZvQ8)

Hi Yenwchen, This seems to be a problem with the image orientation, try using SPM to reorient your images into LPI

**Comment by yenwchen** [comment]
Hi Dr. Hernandez-Castillo @crhernandezc. Thank you for your quick response! The images are in the LPI orientation. We'd appreciate it if you could provide guidance on other potential causes of the issue. Thank you!
