### ISSUE TITLE
Reslicing functional data into SUIT space.

### ISSUE THREAD

**Issue by sankalp492** [jdiedrichsen/suit#16]
Hi,

I have 3 group of cohorts (age: 36 weeks old(neonates), 1 year old and 2 year old)) subjects. I want to Isolate the cerebellum, of all three cohorts and reslice their structural and functional images data into SUIT space. 

I have started with the cerebellar segmentation of 2 year old and and I am facing issues in the third step below.

STEP 1) **Isolation&Segmentation:** 

suit_isolate_seg({'T1*.nii'});

#output image: c_T1_pcereb.nii (cerebellar mask)
	                   c_T1_.nii (cropped T1 image)
                          T1_seg1 (grey matter)
                          T1_seg1 (White matter) 

STEP 2) **Normalizing to SUIT space:** 

job.subjND.gray={'T1_seg1.nii'};
job.subjND.white={'T1_seg2.nii'};
job.subjND.isolation={'c_T1_pcereb.nii'};
suit_normalize_dartel(job);

#output image: Affine_T1_reoriented_seg1.mat, u_a_T1_reoriented_seg1.nii

STEP 3) **Reslicing into SUIT space:**

job.subj.affineTr={'Affine_T1_seg1.mat'}; % Affine transformation 
job.subj.flowfield={'u_a_T1_seg1.nii'}; % This is the flowfield 
job.subj.resample={'c_T1.nii'}; % cropped T1 image
job.subj.mask={'c_T1_pcereb.nii'}; % Mask 
suit_reslice_dartel(job);

#output image: wdc_T1.nii. 
I am able to reslice the structural image (T1) in the SUIT space but I am unable to do so for the functional image.

When I use the above script and replace the cropped T1 image with my preprocessed functional file it gives me the following error:

job.subj.affineTr={'Affine_T1_seg1.mat'}; % Affine transformation 
job.subj.flowfield={'u_a_T1_seg1.nii'}; % This is the flowfield 
job.subj.resample={'func.nii'}; % cropped T1 image
job.subj.mask={'c_T1_pcereb.nii'}; % Mask 
suit_reslice_dartel(job);

**Error:**

**Unable to perform assignment because the indices on the left side are not
compatible with the size of the right side.
Error in suit_reslice_dartel (line 112)
        V(i)=spm_vol(S.resample{i});
Error in Reslice2SUITspace_func (line 5)
suit_reslice_dartel(job);** 

Moreover, if I use fslsplit command to split my functional data into 145 functional slices and then use one of the functional slice as the input, I am able to reslice the functional image into SUIT space. Although it will be a tedious process to isolate all my functional slices and reslice them into the SUIT space and then merge them back.

I was wondering if there is a way you can help me troubleshoot step number 3 where I want to reslice the functional cerebellum in the SUIT space.

Thank you.

**Comment by jdiedrichsen** [comment]
I looks to me that the problem is that the images you are trying to reslice are 4d, rather 3d? Can you confirm?

**Comment by crhernandezc** [comment]
Hi sankalp492, you can split your functional into individual volumes as you mention, I as remember suit reslice dartel does not support 4d, Jorn can confirm that. Regarding your dataset, 1 and 2 year old babies will be well segmented with the regular suit, but for neonates you need to use the neonate version SUIT-N.
