### ISSUE TITLE
Calculate the lobular volume

### ISSUE THREAD

**Issue by augustorachao** [jdiedrichsen/suit#18]
Hello, 
During my work with suit, after successfully isolating, normalizing and reslicing back to the native space, I got stuck in defining the volume of each cerebellar lobule. I used the function suit_vol ('iw file', 'atlas'), but it leads me to a total value of the volume of the cerebellum instead of the volume of each induvidual lobule. 
Has any of you find the same mistake or imagine what I could be doing wrong?
Thank you so much in advance!
Augusto

**Comment by crhernandezc** [comment]
Hi Augusto, the flag is 'Atlas' no 'atlas' it is case sensitive. hope this helps
