### ISSUE TITLE
Isolation error

### ISSUE THREAD

**Issue by saraponti** [jdiedrichsen/suit#19]
Hi all,
I'm trying to use SUIT on a dataset of elderly subjects. I currently correctly segmented almost all my subjects but on 4 (out of 54) the segmentation/isolation is not running correctly. 
I changed the orientation in LPI and I also tried to change the origin of the image in the AC as suggested but I'm still not able to have correct cerebellum isolation. I'm using a T1 MPRAGE plus a PD and an MT map to segment. Do you have any suggestions on how to resolve this issue?
Thanks,

Sara

**Comment by jdiedrichsen** [comment]
Not sure based on what you wrote. When you say it is not "running correctly" is it giving you an error? What does the output look like? How are you using your PD and MT maps? Have you tries only using the T1 alone? 
J

**Comment by crhernandezc** [comment]
Hi Sara, Are you using SPM to reslice the images and center the AC? Sometimes using other tools does not work properly.

**Comment by saraponti** [comment]
Hi, thank you both for your replies.
@jdiedrichsen Here is attached one example of the output of segmentation isolation. It seems the problem is the localization of the cerebellum.
I tried to segment only with the T1 and the output is the same. 

@crhernandezc I'm changing in lpi with Reorient function in nipype. How can I do it in SPM?
Thanks for your help,
Sara
![image](https://user-images.githubusercontent.com/62641191/186013503-4bb4bfeb-b2a7-4399-8894-fe2a924bc589.png)

**Comment by crhernandezc** [comment]
Hey Sara, it is clear to me that there is something wrong with the placement of your image. Again I recommend using SPM to first reorient the image to LPI and then to set the origin on the anterior commissure.

**Comment by saraponti** [comment]
Thanks for your help. 
How can I change the nii orientation in SPM? I figured out how to change the image center, but I cannot understand how to change orientation in SPM, so I would appreciate it if you have any suggestions.
Thank you
