### ISSUE TITLE
anatomical and segmentation have to be in the same space

### ISSUE THREAD

**Issue by katedamme** [jdiedrichsen/suit#2]
Hello!

I am getting the error: "anatomical and segmentation have to be in the same space" for may of my images. I believe the input to suit is expected to be a native space T1 with approx. 1 mm3 voxels, and so I am not sure what is triggering this error, as half of my scans are processing successfully in native space with similar parameters and half are giving this error. 

What should I be adjusting in these individuals? Is this a format compatibility issue or does this indicate something else? 

I appreciate that you'v error coded this, and apologize for not being more adept at interpreting the meaning of the error.  

Thank you.

Kate Damme

**Comment by jdiedrichsen** [comment]
Hi Kate, 

Hmm - they should automatically be in the same space if they are generated directly. 
SUIT looks if there is segmentation already present, and if it is, it uses that. 

Can you try starting the isolation process from a folder, which only has the T1 image in it? 

J

**Comment by katedamme** [comment]
I've re-run them in an isolated folder and reprocessed the images from
dicom to see if it was a file issue, and they appear to be in the correct
format and space (attached but still give the same error.

Error using suit_isolate (line 327)
anatomical and segmentation have to be in the same space

**Comment by crhernandezc** [comment]
Hi Kate,

Before using SUIT there are two steps you should perform. First is to reslice your T1 image into LPI orientation and second set the origin of the image in the anterior commissure. 
if you need more information please email supp.suit@gmail.com and I will follow up.

Carlos
