### ISSUE TITLE
Question about gray matter volume value

### ISSUE THREAD

**Issue by John3290** [jdiedrichsen/suit#20]
I extracted average gray matter volume (GMV) from specific regions of interest from the modulated and smoothed  gray matter segmentation maps from each individual subject in my dataset. 

I am interested in plotting these GMV values for each ROI in a scatterplot and am curious to know what the unit of these GMV values might be. I suspect they are a proportional value. 

**Can you clarify what the denominator of this proportion might be?**  For example, I got a GMV value of 0.4 for the right cerebellar lobule VI for one subject after running SUIT. **What does 0.4 mean?**

**Comment by jdiedrichsen** [comment]
Hi Chelsea - 
GMV values (in group space) in a VBM analysis (I assume that's what you are referring to) are 

p(gray matter for voxel) * size(voxel relative to normal)

So 0.4 for a voxel in atlas space could mean that the corresponding structure in individual space has only 40% gray matter in it, o r was only 40% of the size in normals. 

So you need always to compare the VBM values relative to a healthy control group. 
For a general discussion on VBM methods, see: 
https://en.wikibooks.org/wiki/SPM/VBM

Hope that helps, 

Joern
