### ISSUE TITLE
suit_isolate_seg

### ISSUE THREAD

**Issue by qiumingjing** [jdiedrichsen/suit#21]
Hello:
I'am trying to use the GUI and the Segmentation & Isolation step of the processing stream within the SUIT toolbox. 
I changed the orientation in LPI and I also tried to change the origin of the image in the AC as suggested but I'm still not able to
I keep getting this error:

### **suit_isolate_seg({'rCD100.nii'})
Unrecognized function or variable 'vararginoptions'.
Error in suit_isolate_seg (line 84)
vararginoptions(varargin,{'maskp','keeptempfiles','bb'});**

Do you have any suggestions on how to resolve this issue?

Thank you so much in advance for your help,
mingjing qiu
mingjing_qiu@163.com

**Comment by jdiedrichsen** [comment]
'vararginoptions' is a function included in the SUIT toolbox. 
You need to ensure that the SUIT toolbox main folder is included in the PATH that Matlab uses to find functions. 

See: 
https://www.mathworks.com/help/matlab/ref/path.html
https://www.youtube.com/watch?v=J9wPYMq8XRY

Hope that helps, 

Joern
