### ISSUE TITLE
Lobuli-ROI analysis of atlas

### ISSUE THREAD

**Issue by qiumingjing** [jdiedrichsen/suit#22]
Hello:
Thank you for helping solve the question about “suit_isolate_seg”, and I did it. However, it shows another error when I conduct "Lobuli-ROI analysis of atlas”:
unknown option:regionname
In file "D:\MATLAB\toolbox\spm12\toolbox\suit\templates\vararginoptions.m" (???), function "vararginoptions" at line 44.
In file "D:\MATLAB\toolbox\spm12\toolbox\suit\suit_ROI_summarize.m" (???), function "suit_ROI_summarize" at line 52.
In file "D:\MATLAB\toolbox\spm12\toolbox\suit\suit_lobuli_summarize.m" (???), function "suit_lobuli_summarize" at line 55.
In file "D:\MATLAB\toolbox\spm12\toolbox\suit\suit_run_lobuli_summarize.m" (???), function "suit_run_lobuli_summarize" at line 11.

I have ensured that the SUIT toolbox main folder is included in the PATH that Matlab uses to find functions. 
Do you have any suggestions on how to resolve this issue?

Thank you so much in advance for your help,
mingjing qiu
[mingjing_qiu@163.com]

**Comment by jdiedrichsen** [comment]
Should be fixed in release 3.6
