### ISSUE TITLE
Looping suit_resclice_dartel_inv

### ISSUE THREAD

**Issue by NevMagi** [jdiedrichsen/suit#24]
Dear SUIT team, thank you for an amazing toolbox and all the work on it,

We are trying to move suit lobular and functional (King et al. 2019) parcellations back from SUIT space to native space. We were able to loop all the other functions with the same syntax, but for the inverse reslicing we only managed for one subject at a time. It basically overwrote the first loop (subject 00006) with the second (subject 00007) one. 

We made sure the function was identical to that reporter on the Github, and checked it out. There, we were not able to identify a for-loop structure iterating over different subjects. We tried adding it, but did not get it to work.

So we were wondering if we are miss-specifying the function call or loop, whether the loop is simply missing in the function, or that it is meant to not be looped for a specific reason.

```
This is our for loop (just over 2 subjects to try it out):
subjects = {'00006', '00007'};
for subject=1:length(subjects)
      job.subj(subject).Affine = {['/data/p_02671/data/suit_test/input/sub_' subjects{subject} '_T1/Affine_sub_' subjects{subject} '_T1_seg1.mat']};
      job.subj(subject).flowfield = {['/data/p_02671/data/suit_test/input/sub_' subjects{subject} '_T1/u_a_sub_' subjects{subject} '_T1_seg1.nii']};
      job.subj(subject).resample = {'/data/p_02671/data/suit_test/mdtb/MDTB_maps/atlasesSUIT/Lobules-SUIT.nii'};
      job.subj(subject).ref = {['/data/p_02671/data/suit_test/input/sub_' subjects{subject} '_T1/sub_' subjects{subject} '_T1.nii']};
end
suit_reslice_dartel_inv(job);
```
Giving us the following error:

`Unrecognized field name "Affine".

Error in suit_reslice_dartel_inv (line 32)

load(char(job.Affine));`

Best,
Neville

**Comment by jdiedrichsen** [comment]
suit_reslice_dartel_inv does not take a list of subjects - just a single job of the format:
```
%   job: Structure with fields:
% 
%       job.Affine:     Affine Transform parameter file (Affine*.mat)
%       job.flowfield:  Flowfield file (u_a*.nii)
%       job.resample:   Images that need to be resliced. If this field
%                       doesn't exist, It will reslice the SUIT Lobular 
%                       atlas into the native space.
%       job.ref         Reference image for final geometry of the ouput. 
%                       e.g. initial T1. If this field doesn't exist, final
%                       image will have the same size than SUIT template.
```

So your code should look like: 

```
for subject=1:length(subjects)
      job.Affine = {['/data/p_02671/data/suit_test/input/sub_' subjects{subject} '_T1/Affine_sub_' subjects{subject} '_T1_seg1.mat']};
      job.flowfield = {['/data/p_02671/data/suit_test/input/sub_' subjects{subject} '_T1/u_a_sub_' subjects{subject} '_T1_seg1.nii']};
      job.resample = {'/data/p_02671/data/suit_test/mdtb/MDTB_maps/atlasesSUIT/Lobules-SUIT.nii'};
      job.ref = {['/data/p_02671/data/suit_test/input/sub_' subjects{subject} '_T1/sub_' subjects{subject} '_T1.nii']};
suit_reslice_dartel_inv(job);
end
```

**Comment by NevMagi** [comment]
Thank you, that worked! How silly of us to miss that we put the function outside of the loop. Cheers!
