### ISSUE TITLE
Structural MRI segmentation- Error in reslice into SUIT space

### ISSUE THREAD

**Issue by aortug** [jdiedrichsen/suit#26]
Hello everyone,

Thank you for making SUIT available. I am using it for cerebellum segmentation and volumetric analysis for structural MRI.
I was able to successfully isolate and normalize my subject. However, during reslice into SUIT space I am receiving the following error.
I have checked the previous issues and I couldn't find with a similar one.
If anyone could provide some guidance on this matter, I would greatly appreciate it

Thanks a lot!

>> job.subj.affineTr={'Affine_brainswap_seg1.mat'};
job.subj.flowfield={'u_a_brainswap_seg1.nii'};
job.subj.resample{1}={'c_brainswap.nii'};
job.subj.mask={'c_brainswap_pcereb.nii'};
>> suit_reslice_dartel(job);

SPM12: suit_reslice_dartel (v3.0)                  12:39:51 - 09/08/2023
========================================================================
Error using fileparts (line 32)
Input must be a row vector of characters.

Error in spm_fileparts (line 19)
[pth,nam,ext] = fileparts(fname);

Error in suit_reslice_dartel (line 111)
        [image_dir,image_name,image_ext,image_num]=spm_fileparts(S.resample{i});

**Comment by jdiedrichsen** [comment]
My guess is that : 
job.subj.resample={'c_brainswap.nii'};
or 
job.subj.resample{1}='c_brainswap.nii';

I realize it was wrong in the example
