### ISSUE TITLE
suit_reslice_dartel_inv()" issue

### ISSUE THREAD

**Issue by AndreaBard** [jdiedrichsen/suit#27]
Hello,
I'm interested in performing VBM analyses at the cerebellar level. However, while working with SUIT, I got stuck at the "suit_reslice_dartel_inv()" step.

Below the code and the error:

>> job.Affine={'Affine_pz01_seg1.mat'};
>> job.flowfield={'u_a_pz01_seg1.nii'};
>> job.ref={'pz01.nii'};
>> suit_reslice_dartel_inv(job)
Error using spm_vol>spm_vol_hdr
File "C:\[...]\spm12\toolbox\suit\atlasesSUIT\Lobules-SUIT.nii" does not exist.
Error in spm_vol (line 61)
        v = spm_vol_hdr(deblank(P(i,:)));
Error in suit_reslice_dartel_inv (line 60)
    V = spm_vol(char(job.resample{i}));

The error makes me notice that the following is missing from the SUIT folder: atlasesSUIT\Lobules-SUIT.nii and I cannot find it anywhere. May you tell me where can I find it, please? 

Thank you in advance.
Best Regards,
Andrea

**Comment by jdiedrichsen** [comment]
These atlas files are now in a separate repository: 
https://github.com/DiedrichsenLab/cerebellar_atlases 
[atl-Anatom_space-SUIT_dseg.nii](https://github.com/DiedrichsenLab/cerebellar_atlases/blob/master/Diedrichsen_2009/atl-Anatom_space-SUIT_dseg.nii)

I need to still update the code / documentation to reflect this change - but this should get you going! 

best, 

Joern

**Comment by jdiedrichsen** [comment]
Should me now fixed in release 3.6.
