### ISSUE TITLE
Total cerebellar volume calculation while pcereb mask contains parts of brainstem

### ISSUE THREAD

**Issue by andadw** [jdiedrichsen/suit#28]
Hi,
Want to calculate the total cerebellar volume of young and old participants.
I read that for this I should use the suit_vol function with the pcereb masks as input. What I am wondering about however, is that these masks also contain a part of the brain stem. It also differs per participant how much of the brainstem is included in the masks. Some masks were quite bad and needed a lot of hand correction, however I did not apply any corrections to the brainstem. What is the best way to fix this? Manually removing the brain stem from the mask would take me again a lot of time.

Also the gray and white matter probability maps include parts of the brains stem, so for calculation their total cerebellar volumes I will encounter the same problem.  I would love to get a bit of advice for this subject. Thanks in advance!

**Comment by jdiedrichsen** [comment]
Yes - for normalization purposes the isolation in SUIT includes brainstem structures.
The best option is to define an image with only the structures you want to measure (e.g. cerebellar gray matter) in SUIT space (group level) and then use suit_reslice_inv_dartel to transform them into individual space. Then you can load that image and count the voxels.
