### ISSUE TITLE
Version number displayed in the banner is obsolete

### ISSUE THREAD

**Issue by ylep** [jdiedrichsen/suit#29]
Users at my site are getting confused, thinking that they are running an old version of SUIT (namely 3.3) whereas we are actually up-to-date. Shouldn't the version number in the banner get updated to reflect the release number of SUIT?

https://github.com/jdiedrichsen/suit/blob/a9f2ef2041177ddfb8a98124e969025b1977144c/spm_suit.m#L15

**Comment by jdiedrichsen** [comment]
Now fixed in new release (3.7)
Thanks!
