### ISSUE TITLE
unable to create matlab compiled (mcc) version of SUIT script

### ISSUE THREAD

**Issue by bcmcpher** [jdiedrichsen/suit#4]
I have a simple script that runs suit_isolate_seg, suit_normalize_dartel, and suit_reslice_dartel_inv to align a subject to the SUIT atlas and reslice the labels back into the original T1 space for analysis.

This functions correctly when run within MATLAB. However, I need a compiled version of this code for batch deployment. The code compiles, but upon execution errors out. The current error appears to traceback through to SPM12:

error
""" 
Undefined function or variable 'mysubs_fields'.

Error in cfg_branch (line 59)

Error in cfg_getfile>reg_filter (line 1185)

Error in cfg_getfile (line 177)

Error in spm_select (line 115)

Error in spm_select (line 110)

Error in spm_select (line 97)

Error in spm_jobman (line 173)

Error in suit (line 25)

MATLAB:UndefinedFunction
"""

Is there an established way of compiling SPM that can run with SUIT? If not, what is the most equivalent way of aligning the atlases that does not require SPM?

**Comment by crhernandezc** [comment]
Hey

There is no way to run SUIT without SPM. You are right this problem is related to SPM and not directly to SUIT. Until now we haven't use mcc but I can take a look if you send me your code to supp.suit@gmail.com and I will follow up.

Best 

Carlos
