### ISSUE TITLE
Bug: impossible to overwrite defaults setting for voxel size when normalizing

### ISSUE THREAD

**Issue by Dhaif** [jdiedrichsen/suit#5]
Hello, 

I encoutered a minor bug in the normalization process. In the bath editor ( or the script generated by it), it's impossible to change the final voxel size when normalizing a image in the SUIT space. That bug can be avoid, by manually call the suit_normalize function, and pass the write.vox structure field with the desired resolution.
I didn't overlook the code, but it may seem that there is a confusion in the fieldname of the "write" structure concerning the name the voxel size field: vox, or voxN ?.

Cheers, 

Dhaif.

**Comment by crhernandezc** [comment]
Dear Dhaif,

Thanks for the info, I have look at the code and solved the problem, this was just a typo in the variable definition. In a couple of days, you will be able to download or clone the SUIT Master branch with this problem fixed. However, I do not recommend you to use the old functions, those are depreciated, instead use suit_normalize_dartel for an optimal result. 

Best 

Carlos
